### ISSUE TITLE
[MADE] Preparar camera ready

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-Evostar#31]
Preparar el cámera ready teniendo en cuenta las revisiones. Las instrucciones están aquí (es secreto todavía, se enviará el texto a los correos en breve): http://www.evostar.org/2015/submission_camera_ready.php

Hay que poner en los agradecimientos lo siguiente:

This work has been supported in part by SIPESCA (Programa Operativo FEDER de Andalucía 2007-2013), TIN2011-28627-C04-02 (Spanish Ministry of Economy and Competitivity), SPIP2014-01437  (Dirección General de Tráfico), PRY142/14 (Fundación Pública Andaluza Centro de Estudios Andaluces en la IX Convocatoria de Proyectos de Investigación) and PYR-2014-17 GENIL project (CEI-BIOTIC Granada).

**Comment by raiben** [comment]
He realizado algunos cambios en el paper:
- Solicitado por revisor: cambiar la frase donde aparece "taxes". El revisor propone types pero yo he cambiado la frase completa porque realmente quería decir rates y prefería que se entendiese mejor.
- Añadidos los autores
- Añadidos agradecimientos
- Ajuste mínimos de algunas frases para que quepan mejor
- Cropping de imágenes (márgenes superiores e inferiores)
- Añadida referencia anonimizada
- Ceados los ficheros para la entrega garcia_ortega.tex, garcia_ortega.bib, authors.txt y abstract.txt

Por favor, que alguien con expertise le eche un ojo. Aquí el pdf generado: https://www.dropbox.com/s/qtjqim4jos3ua4i/garcia_ortega.pdf?dl=0

Ah, importante, @fergunet, supongo que tu deberías rellenar lo que piden aparte. Si no es así, dímelo, please.
Also, before 21 January 2015, you also have to send an E-mail to j.willies@napier.ac.uk with the title:
"EvoStar15 attendance confirmation"
which includes the following information:
1. Name of (co)author who will attend EvoStar2015 ________
2. If attendee is a student, their advisor ___________ has been cc-ed into this mail
3. If a VISA is required for the attendee, the application process has started: Not-required / Yes / No.

**Comment by amorag** [comment]
Ha quedado genial. ;)

 

Simplemente recordaros que las referencias deben ordenarse por orden de aparición.

Usad el estilo 'splncs.bst’ y un fichero .bib y deberían salir así. ;D

 

El que vaya a subir la versión final, que siga estas indicaciones, plis:

 

http://www.evostar.org/2015/submission_camera_ready.php

 

¡Talueguico!

 

De: Rubén Héctor [mailto:notifications@github.com] 
Enviado el: domingo, 18 de enero de 2015 20:02
Para: geneura-papers/2015-Evostar
Asunto: Re: [2015-Evostar] [MADE] Preparar camera ready (#31)

 

He realizado algunos cambios en el paper:

*	Solicitado por revisor: cambiar la frase donde aparece "taxes". El revisor propone types pero yo he cambiado la frase completa porque realmente quería decir rates y prefería que se entendiese mejor.
*	Añadidos los autores
*	Añadidos agradecimientos
*	Ajuste mínimos de algunas frases para que quepan mejor
*	Cropping de imágenes (márgenes superiores e inferiores)
*	Añadida referencia anonimizada
*	Ceados los ficheros para la entrega garcia_ortega.tex, garcia_ortega.bib, authors.txt y abstract.txt

Por favor, que alguien con expertise le eche un ojo. Aquí el pdf generado: https://www.dropbox.com/s/qtjqim4jos3ua4i/garcia_ortega.pdf?dl=0

Ah, importante, @fergunet <https://github.com/fergunet> , supongo que tu deberías rellenar lo que piden aparte. Si no es así, dímelo, please.
Also, before 21 January 2015, you also have to send an E-mail to j.willies@napier.ac.uk with the title:
"EvoStar15 attendance confirmation"
which includes the following information:
1. Name of (co)author who will attend EvoStar2015 ________
2. If attendee is a student, their advisor ___________ has been cc-ed into this mail
3. If a VISA is required for the attendee, the application process has started: Not-required / Yes / No.

—
Reply to this email directly or view it on GitHub <https://github.com/geneura-papers/2015-Evostar/issues/31#issuecomment-70420602> .  <https://github.com/notifications/beacon/AC6-WuMYNLv0W04pytKwmIiJbmejFClSks5ni_rDgaJpZM4DRxVM.gif> 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2013.0.3495 / Base de datos de virus: 4257/8949 - Fecha de publicación: 01/17/15

  _____  

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2013.0.3495 / Base de datos de virus: 4257/8887 - Fecha de publicación: 01/07/15
Base de datos de virus interno no está actualizado.

**Comment by raiben** [comment]
Bueno, ya he subido el camera ready. Si alguien comenta cualquier cambio, lo subiré antes del día 21. Si no, daré por cerrado el issue :-)
Saludos!!

**Comment by raiben** [comment]
Hola. Creo que nos hemos cruzado Antonio y yo con las respuestas. @amorag tras ver el pdf me da la impresión de que no está en el orden que indicas, pero que tampoco sigue el orden del fichero bib. En teoría estoy usando el 'splncs.bst'. A ver si alguien es capaz de ver qué falla. Ojo, ya con los ficheros garcia_ortega.tex y garcia_ortega.bib...

**Comment by amorag** [comment]
Pos eso, lo que he comentado un segundo antes de que lo subieras. XD

 

Grachasss.

 

¡Taluego tío!

 

De: Rubén Héctor [mailto:notifications@github.com] 
Enviado el: lunes, 19 de enero de 2015 1:47
Para: geneura-papers/2015-Evostar
CC: Antonio Mora
Asunto: Re: [2015-Evostar] [MADE] Preparar camera ready (#31)

 

Bueno, ya he subido el camera ready. Si alguien comenta cualquier cambio, lo subiré antes del día 21. Si no, daré por cerrado el issue :-)
Saludos!!

—
Reply to this email directly or view it on GitHub <https://github.com/geneura-papers/2015-Evostar/issues/31#issuecomment-70434803> .  <https://github.com/notifications/beacon/AC6-WrGnaIP7p0GA9sftMIbmXC-jLWdlks5njEuUgaJpZM4DRxVM.gif> 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2013.0.3495 / Base de datos de virus: 4257/8953 - Fecha de publicación: 01/18/15

**Comment by amorag** [comment]
Hecho (y subido a GH).

Estabas usando un fichero de estilos bibliográfico que no era. ;)

 

¡Taluego!

 

De: Rubén Héctor [mailto:notifications@github.com] 
Enviado el: lunes, 19 de enero de 2015 1:54
Para: geneura-papers/2015-Evostar
CC: Antonio Mora
Asunto: Re: [2015-Evostar] [MADE] Preparar camera ready (#31)

 

Hola. Creo que nos hemos cruzado Antonio y yo con las respuestas. @amorag <https://github.com/amorag>  tras ver el pdf me da la impresión de que no está en el orden que indicas, pero que tampoco sigue el orden del fichero bib. En teoría estoy usando el 'splncs.bst'. A ver si alguien es capaz de ver qué falla. Ojo, ya con los ficheros garcia_ortega.tex y garcia_ortega.bib...

—
Reply to this email directly or view it on GitHub <https://github.com/geneura-papers/2015-Evostar/issues/31#issuecomment-70435069> .  <https://github.com/notifications/beacon/AC6-Wn4RPLRDtkLQ1_lMB56LL0LGYSBLks5njE0kgaJpZM4DRxVM.gif> 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2013.0.3495 / Base de datos de virus: 4257/8953 - Fecha de publicación: 01/18/15

**Comment by raiben** [comment]
Ok, aplicados algunos cambios en gramática, he cambiado mi afiliación a la UGR y subido el camera ready.

**Comment by fergunet** [comment]
Cierra con "closes #numerico" @raiben
