### ISSUE TITLE
[GPBOT] Preparar Camera Ready

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-Evostar#32]
Preparar el cámera ready teniendo en cuenta las revisiones. Las instrucciones están aquí (es secreto todavía, se enviará el texto a los correos en breve): http://www.evostar.org/2015/submission_camera_ready.php

Hay que poner en los agradecimientos lo siguiente:

This work has been supported in part by SIPESCA (Programa Operativo FEDER de Andalucía 2007-2013), TIN2011-28627-C04-02 (Spanish Ministry of Economy and Competitivity), SPIP2014-01437 (Dirección General de Tráfico), PRY142/14 (Fundación Pública Andaluza Centro de Estudios Andaluces en la IX Convocatoria de Proyectos de Investigación) and PYR-2014-17 GENIL project (CEI-BIOTIC Granada).

**Comment by JJ** [comment]
El TIN ya ha terminado, pero bueno, tampoco pasa nada que se ponga por si
llegar a tiempo para el informe final.

JJ

**Comment by fergunet** [comment]
Deberías haberlo cerrado con commit @deantares jojo
